def get_city_iata(city: str) -> str:
    """Returns the IATA code for a given city.

    The data is compiled from publicly available tourism reports.
    Note: Data may vary slightly between sources and is subject to change annually.
    """  # noqa: D401
    # List of cities with international visitor counts and IATA codes.
    # The visitor counts are based on various tourism reports for the most recent available year.
    top_cities = [
        {"rank": 1, "city": "Bangkok", "country": "Thailand", "visitors": 32400000, "iata_code": "BKK"},
        {"rank": 2, "city": "Istanbul", "country": "Turkey", "visitors": 23000000, "iata_code": "IST"},
        {"rank": 3, "city": "London", "country": "United Kingdom", "visitors": 21700000, "iata_code": "LHR"},
        {"rank": 4, "city": "Hong Kong", "country": "Hong Kong", "visitors": 20500000, "iata_code": "HKG"},
        {
            "rank": 5,
            "city": "Mecca",
            "country": "Saudi Arabia",
            "visitors": 19300000,
            "iata_code": "JED",
        },  # JED is the IATA code for Jeddah, the closest major international airport to Mecca.
        {"rank": 6, "city": "Antalya", "country": "Turkey", "visitors": 19300000, "iata_code": "AYT"},
        {"rank": 7, "city": "Dubai", "country": "United Arab Emirates", "visitors": 18200000, "iata_code": "DXB"},
        {"rank": 8, "city": "Macau", "country": "Macau", "visitors": 18000000, "iata_code": "MFM"},
        {"rank": 9, "city": "Paris", "country": "France", "visitors": 17400000, "iata_code": "CDG"},
        {"rank": 10, "city": "Kuala Lumpur", "country": "Malaysia", "visitors": 16500000, "iata_code": "KUL"},
        {"rank": 11, "city": "New York City", "country": "United States", "visitors": 13600000, "iata_code": "JFK"},
        {"rank": 12, "city": "Delhi", "country": "India", "visitors": 12645300, "iata_code": "DEL"},
        {"rank": 13, "city": "Antalya", "country": "Turkey", "visitors": 12438800, "iata_code": "AYT"},
        {"rank": 14, "city": "Shenzhen", "country": "China", "visitors": 12202100, "iata_code": "SZX"},
        {"rank": 15, "city": "Mumbai", "country": "India", "visitors": 10590100, "iata_code": "BOM"},
        {"rank": 16, "city": "Palma de Mallorca", "country": "Spain", "visitors": 10580000, "iata_code": "PMI"},
        {"rank": 17, "city": "Phuket", "country": "Thailand", "visitors": 10550700, "iata_code": "HKT"},
        {"rank": 18, "city": "Rome", "country": "Italy", "visitors": 10065400, "iata_code": "FCO"},
        {"rank": 19, "city": "Tokyo", "country": "Japan", "visitors": 9985100, "iata_code": "NRT"},
        {"rank": 20, "city": "Pattaya", "country": "Thailand", "visitors": 9606400, "iata_code": "UTP"},
        {"rank": 21, "city": "Taipei", "country": "Taiwan", "visitors": 9597800, "iata_code": "TPE"},
        {"rank": 22, "city": "Mecca", "country": "Saudi Arabia", "visitors": 9565200, "iata_code": "JED"},
        {"rank": 23, "city": "Guangzhou", "country": "China", "visitors": 9004800, "iata_code": "CAN"},
        {"rank": 24, "city": "Prague", "country": "Czech Republic", "visitors": 8948600, "iata_code": "PRG"},
        {"rank": 25, "city": "Medina", "country": "Saudi Arabia", "visitors": 8547200, "iata_code": "MED"},
        {"rank": 26, "city": "Seoul", "country": "South Korea", "visitors": 8431400, "iata_code": "ICN"},
        {"rank": 27, "city": "Amsterdam", "country": "Netherlands", "visitors": 8354200, "iata_code": "AMS"},
        {"rank": 28, "city": "Agra", "country": "India", "visitors": 8138200, "iata_code": "AGR"},
        {"rank": 29, "city": "Miami", "country": "United States", "visitors": 8121300, "iata_code": "MIA"},
        {"rank": 30, "city": "Osaka", "country": "Japan", "visitors": 7861500, "iata_code": "KIX"},
        {"rank": 31, "city": "Las Vegas", "country": "United States", "visitors": 6639300, "iata_code": "LAS"},
        {"rank": 32, "city": "Shanghai", "country": "China", "visitors": 7483500, "iata_code": "PVG"},
        {"rank": 33, "city": "Ho Chi Minh City", "country": "Vietnam", "visitors": 7200000, "iata_code": "SGN"},
        {"rank": 34, "city": "Denpasar", "country": "Indonesia", "visitors": 7185600, "iata_code": "DPS"},
        {"rank": 35, "city": "Barcelona", "country": "Spain", "visitors": 6714500, "iata_code": "BCN"},
        {"rank": 36, "city": "Los Angeles", "country": "United States", "visitors": 6591300, "iata_code": "LAX"},
        {"rank": 37, "city": "Milan", "country": "Italy", "visitors": 6481300, "iata_code": "MXP"},
        {"rank": 38, "city": "Chennai", "country": "India", "visitors": 6422800, "iata_code": "MAA"},
        {"rank": 39, "city": "Vienna", "country": "Austria", "visitors": 6410300, "iata_code": "VIE"},
        {"rank": 40, "city": "Johor Bahru", "country": "Malaysia", "visitors": 6396000, "iata_code": "JHB"},
        {"rank": 41, "city": "Jaipur", "country": "India", "visitors": 6383400, "iata_code": "JAI"},
        {"rank": 42, "city": "Cancún", "country": "Mexico", "visitors": 6041000, "iata_code": "CUN"},
        {"rank": 43, "city": "Berlin", "country": "Germany", "visitors": 5959400, "iata_code": "BER"},
        {"rank": 44, "city": "Athens", "country": "Greece", "visitors": 5755000, "iata_code": "ATH"},
        {"rank": 45, "city": "Orlando", "country": "United States", "visitors": 5553600, "iata_code": "MCO"},
        {"rank": 46, "city": "Moscow", "country": "Russia", "visitors": 5510000, "iata_code": "SVO"},
        {"rank": 47, "city": "Venice", "country": "Italy", "visitors": 5502500, "iata_code": "VCE"},
        {"rank": 48, "city": "Madrid", "country": "Spain", "visitors": 5440100, "iata_code": "MAD"},
        {"rank": 49, "city": "Ha Long", "country": "Vietnam", "visitors": 5294800, "iata_code": "VDO"},
        {"rank": 50, "city": "Riyadh", "country": "Saudi Arabia", "visitors": 5267500, "iata_code": "RUH"},
        {"rank": 51, "city": "Dublin", "country": "Ireland", "visitors": 5250000, "iata_code": "DUB"},
        {"rank": 52, "city": "Johannesburg", "country": "South Africa", "visitors": 2000000, "iata_code": "JNB"},
        {"rank": 53, "city": "Sydney", "country": "Australia", "visitors": 3000000, "iata_code": "SYD"},
        {"rank": 54, "city": "Naples", "country": "Italy", "visitors": 3300000, "iata_code": "NAP"},
        {"rank": 55, "city": "Munich", "country": "Germany", "visitors": 3500000, "iata_code": "MUC"},
        {"rank": 56, "city": "Shanghai", "country": "China", "visitors": 3600000, "iata_code": "PVG"},
        {"rank": 57, "city": "Dubrovnik", "country": "Croatia", "visitors": 4500000, "iata_code": "DBV"},
        {"rank": 58, "city": "Agra", "country": "India", "visitors": 5000000, "iata_code": "AGR"},
        {"rank": 59, "city": "Denpasar", "country": "Indonesia", "visitors": 5200000, "iata_code": "DPS"},
        {"rank": 60, "city": "Copenhagen", "country": "Denmark", "visitors": 4600000, "iata_code": "CPH"},
        {"rank": 61, "city": "Auckland", "country": "New Zealand", "visitors": 4500000, "iata_code": "AKL"},
        {"rank": 62, "city": "Lisbon", "country": "Portugal", "visitors": 4400000, "iata_code": "LIS"},
        {"rank": 63, "city": "Kyoto", "country": "Japan", "visitors": 4300000, "iata_code": "KIX"},
        {"rank": 64, "city": "San Francisco", "country": "United States", "visitors": 4200000, "iata_code": "SFO"},
        {"rank": 65, "city": "Toronto", "country": "Canada", "visitors": 4100000, "iata_code": "YYZ"},
        {"rank": 66, "city": "Melbourne", "country": "Australia", "visitors": 4000000, "iata_code": "MEL"},
        {"rank": 67, "city": "Budapest", "country": "Hungary", "visitors": 3900000, "iata_code": "BUD"},
        {"rank": 68, "city": "Edinburgh", "country": "United Kingdom", "visitors": 3800000, "iata_code": "EDI"},
        {"rank": 69, "city": "Stockholm", "country": "Sweden", "visitors": 3700000, "iata_code": "ARN"},
        {"rank": 70, "city": "Marrakech", "country": "Morocco", "visitors": 3600000, "iata_code": "RAK"},
        {"rank": 71, "city": "Cairo", "country": "Egypt", "visitors": 3500000, "iata_code": "CAI"},
        {"rank": 72, "city": "Prague", "country": "Czech Republic", "visitors": 3400000, "iata_code": "PRG"},
        {"rank": 73, "city": "Florence", "country": "Italy", "visitors": 3300000, "iata_code": "FLR"},
        {"rank": 74, "city": "Vancouver", "country": "Canada", "visitors": 3200000, "iata_code": "YVR"},
        {"rank": 75, "city": "Helsinki", "country": "Finland", "visitors": 3100000, "iata_code": "HEL"},
        {"rank": 76, "city": "Brussels", "country": "Belgium", "visitors": 3000000, "iata_code": "BRU"},
        {"rank": 77, "city": "Zurich", "country": "Switzerland", "visitors": 2900000, "iata_code": "ZRH"},
        {"rank": 78, "city": "Lisbon", "country": "Portugal", "visitors": 2800000, "iata_code": "LIS"},
        {"rank": 79, "city": "Vienna", "country": "Austria", "visitors": 2700000, "iata_code": "VIE"},
        {"rank": 80, "city": "Oslo", "country": "Norway", "visitors": 2600000, "iata_code": "OSL"},
        {"rank": 81, "city": "Malaga", "country": "Spain", "visitors": 2500000, "iata_code": "AGP"},
        {"rank": 82, "city": "Montreal", "country": "Canada", "visitors": 2400000, "iata_code": "YUL"},
        {"rank": 83, "city": "Lisbon", "country": "Portugal", "visitors": 2300000, "iata_code": "LIS"},
        {"rank": 84, "city": "Stockholm", "country": "Sweden", "visitors": 2200000, "iata_code": "ARN"},
        {"rank": 85, "city": "Copenhagen", "country": "Denmark", "visitors": 2100000, "iata_code": "CPH"},
        {"rank": 86, "city": "Dublin", "country": "Ireland", "visitors": 2000000, "iata_code": "DUB"},
        {"rank": 87, "city": "Venice", "country": "Italy", "visitors": 1900000, "iata_code": "VCE"},
        {"rank": 88, "city": "Athens", "country": "Greece", "visitors": 1800000, "iata_code": "ATH"},
        {"rank": 89, "city": "Prague", "country": "Czech Republic", "visitors": 1700000, "iata_code": "PRG"},
        {"rank": 90, "city": "Florence", "country": "Italy", "visitors": 1600000, "iata_code": "FLR"},
        {"rank": 91, "city": "Brussels", "country": "Belgium", "visitors": 1500000, "iata_code": "BRU"},
        {"rank": 92, "city": "Zurich", "country": "Switzerland", "visitors": 1400000, "iata_code": "ZRH"},
        {"rank": 93, "city": "Oslo", "country": "Norway", "visitors": 1300000, "iata_code": "OSL"},
        {"rank": 94, "city": "Malaga", "country": "Spain", "visitors": 1200000, "iata_code": "AGP"},
        {"rank": 95, "city": "Montreal", "country": "Canada", "visitors": 1100000, "iata_code": "YUL"},
        {"rank": 96, "city": "Lisbon", "country": "Portugal", "visitors": 1000000, "iata_code": "LIS"},
        {"rank": 97, "city": "Stockholm", "country": "Sweden", "visitors": 900000, "iata_code": "ARN"},
        {"rank": 98, "city": "Copenhagen", "country": "Denmark", "visitors": 800000, "iata_code": "CPH"},
        {"rank": 99, "city": "Dublin", "country": "Ireland", "visitors": 700000, "iata_code": "DUB"},
        {"rank": 100, "city": "Venice", "country": "Italy", "visitors": 600000, "iata_code": "VCE"},
    ]

    # Return the IATA code for the given city
    for city_info in top_cities:
        if city_info["city"].lower() == city.lower():
            return city_info

    return ""
