from core.capability import Capability


class ResponseFormatter(Capability):
    """A class to format responses generated by the agent."""

    def __init__(self):
        super().__init__("response_formatter")

    def format_response(self, response: str, format_type: type):
        """Format the response based on the specified format type."""
        raise NotImplementedError("This method should be implemented by subclasses.")
