from capabilities.response_formatter import ResponseFormatter


class ResponseFormatterSpoof(ResponseFormatter):
    """A class to format responses generated by the agent."""

    def format_response(self, response: str, format_type: type):
        """Format the response based on the specified format type."""

        if format_type == str:
            return response
        else:
            raise ValueError(f"Unsupported format type: {format_type}")
